### ISSUE TITLE
Запуск на Windows

### ISSUE THREAD

**Issue by koutsenko** [alekseyBatuhtin/robo_test#1]
Похоже что в package.json платформозависимые конструкции.
Не удается запустить или собрать под виндой.
Возможно исправить?

**Comment by alekseyBatuhtin** [comment]
Конечно. Перейти на linux/mac, например.
Но вообще неплохо было если вы ещё ошибку приложили бы.

**Comment by alekseyBatuhtin** [comment]
@koutsenko добавил `cross-env` сборка должна работать. Если не удастся запустить, то проблема скорее всего может быть в путях [здеся].(https://github.com/alekseyBatuhtin/robo_test/blob/master/webpack/webpack.config.js#L5)

**Comment by koutsenko** [comment]
Да, заработало, спасибо
